# Generated by Django 4.0.3 on 2022-04-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('ar_name', models.CharField(blank=True, max_length=200)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('ar_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('wilaya_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.wilaya')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
