# Generated by Django 4.0.3 on 2022-05-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
