# Generated by Django 4.0.3 on 2022-04-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_contact_website_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_website',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
