# Generated by Django 4.0.3 on 2022-04-19 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_agency_address'),
        ('vehicle', '0002_alter_vehicle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_cars', to='agency.agency'),
        ),
    ]
