# Generated by Django 4.0.3 on 2022-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_vehicle_owned_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='make',
            new_name='make_id',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model',
            new_name='name',
        ),
        migrations.AddField(
            model_name='model',
            name='series',
            field=models.CharField(blank=True, help_text='Model', max_length=100, null=True),
        ),
    ]
