# Generated by Django 4.0.3 on 2022-05-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_option_vehicle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='vehicle', to='vehicle.option'),
        ),
    ]
