# Generated by Django 4.0.3 on 2022-05-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_alter_vehicle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
