# Generated by Django 4.0.3 on 2022-06-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_vehicle_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='options',
            field=models.ManyToManyField(null=True, related_name='vehicle', to='vehicle.option'),
        ),
    ]
