# Generated by Django 4.0.3 on 2022-03-31 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Make', max_length=100)),
                ('model', models.CharField(help_text='Model', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Vehicle price', max_digits=8)),
                ('year', models.PositiveSmallIntegerField(help_text='Vehicle year')),
                ('vehicle_type', models.CharField(blank=True, choices=[('c', 'Cars'), ('m', 'Motocycles - Scooters'), ('tk', 'Truck'), ('v', 'Van'), ('b', 'Bus'), ('bt', 'Boats')], default='c', help_text='Vehicle type', max_length=2, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(help_text='Small description (1000)', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agencyAdminstration.vehiclemodel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
