# Generated by Django 4.0.3 on 2022-04-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencyAdminstration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/vehicle_images/%y/%m/%d')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyAdminstration.vehicle')),
            ],
        ),
    ]
