# Generated by Django 4.0.3 on 2022-04-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyAdminstration', '0002_vehicleimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='vehicle_images/%y/%m/%d'),
        ),
    ]
