# Generated by Django 4.0.3 on 2022-04-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencyAdminstration', '0004_vehicle_owned_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='vehicleimages',
            old_name='vehicle',
            new_name='belong_to',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='thumbnail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agencyAdminstration.vehicleimages'),
        ),
    ]
