# Generated by Django 4.0.3 on 2022-04-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencyAdminstration', '0006_alter_vehicle_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Transmission name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Engine name', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agencyAdminstration.vehicleengine'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='agencyAdminstration.transmission'),
        ),
    ]
