# Generated by Django 4.0.3 on 2022-04-06 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencyAdminstration', '0009_alter_vehicleimages_belong_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agencyAdminstration.vehiclemake'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyAdminstration.vehiclemake'),
        ),
    ]
