# Generated by Django 4.0.3 on 2022-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_remove_agency_location_location_city_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='image',
            field=models.ImageField(blank=True, default='default/default_profile_image.svg', upload_to='profile_images/%y/%m/%d'),
        ),
    ]
