# Generated by Django 4.0.3 on 2022-04-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_agency_city_agency_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='bio',
            field=models.TextField(blank=True, help_text='(500)', max_length=500),
        ),
    ]
