# Generated by Django 4.0.3 on 2022-04-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_agency_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
