# Generated by Django 4.0.3 on 2022-04-28 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
        ('agency', '0008_alter_agency_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.commune'),
        ),
        migrations.AddField(
            model_name='agency',
            name='wilaya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.wilaya'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
