# Generated by Django 4.0.3 on 2022-05-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_agency_commune_agency_wilaya_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='available_cars_count',
            field=models.IntegerField(default=0),
        ),
    ]
