# Generated by Django 4.0.3 on 2022-05-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_remove_agency_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
