# Generated by Django 4.0.3 on 2022-04-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0003_alter_vehicle_owned_by'),
        ('agency', '0008_alter_agency_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Please insert your Firstname', max_length=100)),
                ('last_name', models.CharField(help_text='Please insert your Lasttname', max_length=100)),
                ('mobile', models.CharField(help_text='This field is important!', max_length=12)),
                ('email', models.CharField(blank=True, max_length=12, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], help_text='Please select gender', max_length=1)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, help_text='(500)', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Vehicle price', max_digits=8)),
                ('status', models.CharField(choices=[('p', 'Postponed'), ('a', 'Accepted'), ('r', 'Refused')], default='p', max_length=1)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.client')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
