# Generated by Django 4.0.3 on 2022-04-23 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_alter_agency_user'),
        ('order', '0002_alter_order_options_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agency'),
        ),
    ]
